version: '3.7'
services:
  kafka-made-simple:
    image: kafka-made-simple
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - mongo
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/yourdbname

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input-topic:1:1,processed-topic:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

networks:
  default:
    name: my-network
